# 서문 {-}

세 명의 저자와 함께 일하게 된 것을 큰 행운이라고 생각합니다. 그들은 현명하고 겸손한 분들이며, 그들의 사례와 지도 덕분에 전문성을 키우는 데 많은 도움을 받았습니다. Uday는 데이터 과학의 모범 사례와 효과적인 리더가 되는 방법에 대한 깊은 지식을 심어 주었고, Ken은 딥러닝에 대한 대화를 통해 멘토링했으며, Mitch와 저는 복잡한 문제에 접근하는 최선의 방법, 프로덕션 모델을 구현하는 방법, 그리고 커피를 만드는 방법에 대해 수많은 시간을 함께 토론하며 깊은 기술적 대화를 나눴습니다. 두 사람의 놀라운 지식과 노력이 이 책으로 탄생하게된 것을 보게 되어 정말 기쁩니다.

저는 _The Book of Why_를 읽은 이후로 인과관계에 관심이 많았습니다(추천해 주셔서 감사합니다, Mitch!). 괴짜로서 이론에 관한 책을 읽는 것을 좋아하지만, 실제적인 측면은 직접 해보기 전까지는 만족하지 않았어요. 안타깝게도 인과관계에 대한 이론에서 실무로 넘어가는 것은 어렵고, 그렇게 할 수 있는 리소스도 제한되어 있죠. 이 책은 그런 필요를 완벽하게 충족시켜 줄 것입니다. _응용 인과추론_은 이 주제에 대해 잘 쓰여지고 심층적으로 다루고 있으며, 역사와 이론에 대한 포괄적인 개요를 제공할 뿐만 아니라(추가 읽기를 위한 많은 자료도 제공해요), 실제 적용측면에서 진가를 발휘합니다. 이 복잡한 주제를 쉽게 이해하고 다양한 영역에 적용할 수 있도록 각 장마다 수많은 구체적인 예시와 그림이 있어요. 사례 연구는 잘 설계되고 흥미진진하며 실습을 위한 환상적인 기회를 제공해줄 것입니다. 그리고 사용된 오픈소스 도구는 접근성이 좋고, 다루어진 문제들은 실제 세계의 예시와 데이터입니다.

이 책은 자연어 처리, 컴퓨터 비전, 시계열 분석, 강화학습과 같은 다양하고 복잡한 머신러닝 적용사례에 인과관계를 접목하는 방법을 다룹니다. 또한 알고리즘 편향과 모델 공정성, 그리고 인과관계를 사용하여 이러한 편향의 직/간접적 영향을 이해하고 정량화하는 방법에 대한 장도 포함되어 있습니다. 윤리적인 머신러닝 모델을 훈련하는 것은 매우 중요하며, 이를 통해 인과추론 방법론을 여러분의 도구상자에 추가할 수 있을 거예요.

이 책은 인과관계에 대한 지식을 키우고 이를 시도해 볼 수 있는 도구를 제공하는 데 있어 저에게 기초가 되었습니다. 데이터 과학자나 데이터 직군에 있는 분이라면 이 책을 꼭 읽어보시기 바랍니다! 인과관계가 무엇인지, 왜 인과관계에 관심을 가져야 하는지, 가장 중요한 것은 이론에서 실제 적용으로 나아가는 방법 등 인과관계에 대해 더 깊이 이해하는 데 도움이 될 것입니다.

<cite>Christi French, Ph.D.<br>Chief Data Scientist, Azra AI</cite>